server:
  port: 8021
spring:
  application:
    name: sentinel-demo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.128:8863
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
      datasource:
        dsflow:
          nacos:
            server-addr: 192.168.6.128:8863
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: flow